"""Phase-1 (3): bring the 9 research-catalog reference tables in line with the
post-rename node names (A class, 889 ref fan-out edges). The committed tables were
generated by build_refs.py from skill-index.md with CLEAN descriptions; that source
is consumed and non-idempotent, and refactory_source's HTML descriptions are mojibake.
So we RENAME the skill column in-place (bare -> <pkg>-<old>) via lib.rename_map(),
preserving the committed descriptions, then verify each table's skill set equals the
ref/<pkg> out-edge target set. Catalog body's 9 package pointers (B class) verified.
NOT frontmatter - catalog directory completeness only. --apply to write."""
import argparse, re
from pathlib import Path
import lib_refactory as lib

REF_DIR = lib.SKILL_DIR / "research-catalog" / "references"
CATALOG_MD = lib.SKILL_DIR / "research-catalog" / "SKILL.md"
ROW_RE = re.compile(r"^\|\s*([\w-]+)\s*\|\s*([a-z0-9][a-z0-9.\-]*)\s*\|\s*(.*?)\s*\|\s*$")


def _expected_targets():
    """pkg -> {skill name} from ref/<pkg> out-edges (post-rename, in refactory_source)."""
    d = lib.load_source()
    out = {}
    for e in d["edges"]:
        if e["from"].startswith("ref/"):
            out.setdefault(e["from"][4:], set()).add(e["to"])
    return out


def build_tables():
    """pkg -> [(layer, skill_name, desc)] read from each committed table with the
    skill column renamed (bare -> <pkg>-<old>) where the rename map applies."""
    rm = lib.rename_map()                          # {(pkg, old_bare): new_bare}
    tabs = {}
    for fp in sorted(REF_DIR.glob("*.md")):
        pkg = fp.stem
        rows = []
        for line in fp.read_text(encoding="utf-8").splitlines():
            m = ROW_RE.match(line)
            if not m:
                continue
            layer, skill, desc = m.group(1), m.group(2), m.group(3)
            if layer in ("Layer", "---"):
                continue
            new = rm.get((pkg, skill), skill)      # rename if collision/wrapper
            rows.append((layer, new, desc))
        tabs[pkg] = rows
    return tabs


def render_table(pkg, rows):
    head = (f"# {pkg} — skill table\n\n{len(rows)} skills. "
            "Sorted by layer (campaign→strategy→tactic→sop), then name.\n\n"
            "| Layer | Skill | Description |\n| --- | --- | --- |\n")
    body = "".join(f"| {l} | {s} | {d} |\n" for l, s, d in rows)
    return head + body


def verify(tabs):
    """Assert each table's skill set equals the refactory ref/<pkg> target set."""
    exp = _expected_targets()
    problems = []
    for pkg, rows in tabs.items():
        got = {s for _, s, _ in rows}
        miss, extra = exp.get(pkg, set()) - got, got - exp.get(pkg, set())
        if miss or extra:
            problems.append((pkg, sorted(miss)[:5], sorted(extra)[:5]))
    return problems


def apply(tabs):
    REF_DIR.mkdir(parents=True, exist_ok=True)
    for pkg, rows in tabs.items():
        (REF_DIR / f"{pkg}.md").write_text(render_table(pkg, rows), encoding="utf-8")
    return len(tabs)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    tabs = build_tables()
    probs = verify(tabs)
    print(f"tables={len(tabs)} total_rows={sum(len(v) for v in tabs.values())}")
    if probs:
        for pkg, miss, extra in probs:
            print(f"  MISMATCH {pkg}: miss={miss} extra={extra}")
        raise SystemExit("ref tables do not match refactory_source targets")
    if CATALOG_MD.exists():
        ct = CATALOG_MD.read_text(encoding="utf-8")
        missing_ptrs = [p for p in tabs if f"references/{p}.md" not in ct]
        print(f"catalog pointers missing: {missing_ptrs or 'none'}")
    print(f"wrote {apply(tabs)} tables" if a.apply else "DRY-RUN")


if __name__ == "__main__":
    main()
